### ISSUE TITLE
Analyze CLJX file extension

### ISSUE THREAD

**Issue by lynaghk** [gdeer81/marginalia#103]
The core#format-sources fn has hardcoded regex that match `.clj` and `.cljs`.
Is there a way to tell marginalia to look at `.cljx` files without forking the project?

**Comment by msattel** [comment]
I have the same problem with ``.cljc`` files.

**Comment by msattel** [comment]
Just noticed that ``.cljx`` and ``.cljc`` are supported now, according to the last change in ``core.clj``. I will retest it with the latest version. Thank you.

**Comment by gdeer81** [comment]
I'm going to close this issue. Please reopen if your tests fail.
