### ISSUE TITLE
Can not find namespaces

### ISSUE THREAD

**Issue by htenes** [gdeer81/marginalia#123]
The build succeeds, but only dependencies are listed in the uberdoc.html, namespaces are empty.

Here is the maven output

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building lwjg.clojure.test 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- zi:0.5.0:marginalia (default-cli) @ lwjg.clojure.test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.302s
[INFO] Finished at: Tue Jan 07 12:14:13 CET 2014
[INFO] Final Memory: 11M/27M
[INFO] ------------------------------------------------------------------------

![marginalia](https://f.cloud.github.com/assets/2001139/1858471/0d2003c2-778d-11e3-8139-1cd301627b0c.png)

**Comment by tsmacdonald** [comment]
@htenes Do you remember any more details about this? Is there anything notable about the codebase you were running it on? (Do you know which version of Marginalia it was?)

**Comment by tsmacdonald** [comment]
Closing this since it's 10 years old and there's have been more recent similar reports.
