### ISSUE TITLE
Code watching / docs autoreloading

### ISSUE THREAD

**Issue by atroche** [gdeer81/marginalia#143]
Hey guys,

I'd love it if I could run something like `lein marg --watch` and it would watch for changes to my source files and regenerate docs (rather than having to run it manually every time). Would this be a hard change? Or does the functionality already exist and I somehow missed it?

**Comment by benjamin-bader** [comment]
You can do this without code changes using `guard`, the Ruby gem, configuring it to watch your source files and to invoke marginalia on updates.

If you wanted to use only Clojure for this, the right place to implement this is in https://github.com/gdeer81/lein-marginalia.
