### ISSUE TITLE
Marginalia 0.8.1

### ISSUE THREAD

**Issue by fgiasson** [gdeer81/marginalia#151]
Is there any plan for releasing Marginalia 0.8.1 based on the latest fixes?

**Comment by benjamin-bader** [comment]
That depends on @gdeer81; I believe he is the only one with the ability to deploy a new "official" release.

**Comment by fgiasson** [comment]
Hi @benjamin-bader,

Yeah what I thought. I was wondering since I think that a new version would be helpful sometime soon, since I have projects that uses the 0.8.1 snapshot but that are released using 0.8.0 because it is still a snapshot even if I use the new exclusion feature (not critical, but sub-optimal :) )

**Comment by gdeer81** [comment]
Yes, I'm preparing to cut a new release this week based on the latest fixes.
![star](https://cloud.githubusercontent.com/assets/1340575/7118382/748bc3a0-e1c4-11e4-959c-02a3975ee069.jpg)

**Comment by fgiasson** [comment]
@gdeer81 great thanks!

**Comment by kenny-evitt** [comment]
Given that version 9 was released in March, I think this can be safely closed.
