### ISSUE TITLE
Marginalia waits a long time for agents to shut down

### ISSUE THREAD

**Issue by eigenhombre** [gdeer81/marginalia#159]
Marginalia should probably call `shutdown-agents` when it finishes, in any of the top-level forms cause futures to be spawned.  `lein marg` on one project I tested sits and waits for ~60 seconds which `shutdown-agents` should avoid.

**Comment by gdeer81** [comment]
Thanks for reporting this. Do you have an example codebase I can test against?

**Comment by eigenhombre** [comment]
That looks like that should do it... thank you very much!
