### ISSUE TITLE
Incompatibility in matchSymbol with Clojure 1.9.0-beta1

### ISSUE THREAD

**Issue by jamesaoverton** [gdeer81/marginalia#166]
I'm seeing errors like the following when using Clojure 1.9.0-beta1:

```
Exception in thread "main" java.lang.RuntimeException:
Problem parsing near line 1 < [clojure.string :as string]))> 
original reported cause is
java.lang.NoSuchMethodException: clojure.lang.LispReader.matchSymbol(java.lang.String) -- 
java.lang.NoSuchMethodException: clojure.lang.LispReader.matchSymbol(java.lang.String),
compiling:(/tmp/form-init158705263188885192.clj:1:72)
```

I see that Marginalia is calling `clojure.lang.LispReader.matchSymbol(java.lang.String)` here: https://github.com/gdeer81/marginalia/blob/master/src/marginalia/parser.clj#L118

However the signature of `matchSymbol` changed to `(String s, Resolver resolver)` with this commit: https://github.com/clojure/clojure/commit/dd851520f0c94727591b8b605176755b2a993b0e#diff-3a5dca122734225f3f60263876401aebR405

**Comment by benjamin-bader** [comment]
Good catch!  Would you like to submit a PR?

**Comment by jamesaoverton** [comment]
Simply changing to the new signature will break compatibility for anyone using Marginalia with previous versions of Clojure. A try/catch for the new/old signature should work, but isn't pretty. What do you think?

**Comment by benjamin-bader** [comment]
Try-catch would work.  It might be nice to do that once up-front, when defining the `match-symbol` var, so we don't slow down parsing too much.

My Clojure is _really_ rusty, but I'm thinking something along the lines of

```clj
(def match-symbol
  (if *reader-resolver*
    (fn [s] (call-method clojure.lang.LispReader :matchSymbol [String, <typeof Resolver>] nil s *reader-resolver*)
    (fn [s] (call-method clojure.lang.LispReader :matchSymbol [String] nil s)))
```

I don't remember how to spell a nested Java class in Clojure syntax, so my apologies there.

**Comment by jamesaoverton** [comment]
Good idea. I'll give that a try and make a PR as soon as I have a bit of time.
