### ISSUE TITLE
Docstrings should be dedented

### ISSUE THREAD

**Issue by anntzer** [gdeer81/marginalia#81]
Consider the following example:

```
(defn f
  "A docstring

  - a list
  - another element

  Rest of the docstring."
  (function contents))
```

The markdown parser sees that the last line of the docstring is indented, so believes that it is part of the second element of the list.  Instead, I think the parser should first remove two leading spaces from each line of the docstring (except the first one) before feeding the result to markdown (à la textwrap.dedent function that Python has).

**Comment by seancorfield** [comment]
I ran into this as well. One thing to watch out for is that there are three common styles for docstrings:

      "first line indented
    subsequent lines flush
    to the left margin"

      "first line indented
       subsequent lines 
       lined up with the text"

      "first line indented
      subsequent lines
      lined up with the quote"

So whatever the parser does has to work with all three styles -- or else you need options to control how to behave.

**Comment by arichiardi** [comment]
There was a proposal long time ago of having a "standard" format for docstrings: Bozhidar was bc pushing for the same format that elisp has.
I think some sort of standard is enforced in emacs when you indent (it follows the `clojure-style-guide` specs if I correctly understood).
It is probably a good idea to parse the three styles if possible, but I would really go for one only (the elisp one) if not.

**Comment by seancorfield** [comment]
@arichiardi You are correct https://github.com/bbatsov/clojure-style-guide#documentation

And it specifically says the third form above is the "right" way. I think replacing `"\n  "` with `"\n"` would be the simplest way to support what this issue requests without messing too much (and it could be done directly at the point where a `docstring` is extracted from the source I think?).

**Comment by seancorfield** [comment]
I didn't add any tests for this (I'm a _bad OSS developer_) because I really wanted to test how the HTML, generated from the markdown, would look in a browser... so I did some manual testing instead.

**Comment by gdeer81** [comment]
looks good now, closing out this issue
